{{- $chartName := include "discrete-overseer-creator.name" . -}}
{{- $tracingUrl := include "discrete-overseer-creator.tracingUrl" . -}}
{{- $metricsUrl := include "discrete-overseer-creator.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  JOB_MANAGER_URL: {{ .Values.rasterCommon.serviceUrls.jobManager | quote }}
  SYNC_SERVICE_URL: {{ .Values.rasterCommon.serviceUrls.syncManager | quote }}
  MAP_PUBLISHING_SERVICE_URL: {{ .Values.rasterCommon.serviceUrls.mapproxyApi | quote }}
  PUBLIC_MAP_SERVER_URL: {{ .Values.env.mapServerPublicDNS | quote }}
  CATALOG_PUBLISHING_SERVICE_URL: {{ .Values.rasterCommon.serviceUrls.catalogManager | quote }}
  MAP_SERVER_CACHE_TYPE: {{ .Values.rasterCommon.storage.tilesStorageProvider | quote }}
  DISPLAY_NAME_DIR: {{ .Values.env.displayNameDir | quote }}
  VALID_FILE_EXTENSIONS: {{ .Values.env.validFileExtensions | quote }}
  TILING_ZOOM_GROUPS: {{ .Values.env.tilingZoomGroups | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.resetTimeout | quote }}
  LINK_TEMPLATE: {{ tpl (.Files.Get "config/linkTemplates.template") . | quote }}
  LAYER_SOURCE_DIR: {{ .Values.env.layerSourceDir | quote }}
  SHOULD_SYNC: {{ .Values.env.shouldSync | quote }}
  INGESTION_NEW_JOB_TYPE: {{ .Values.rasterCommon.jobManagement.ingestion.new.jobType | quote }}
  INGESTION_SPLIT_TILES_TASK_TYPE: {{ .Values.rasterCommon.jobManagement.ingestion.new.splitTilesTaskType | quote }}
  INGESTION_UPDATE_JOB_TYPE: {{ .Values.rasterCommon.jobManagement.ingestion.update.jobType | quote }}
  INGESTION_MERGE_TASK_TYPE: {{ .Values.rasterCommon.jobManagement.ingestion.update.mergeTilesTaskType | quote }}
  BBOX_SIZE_TILES: {{ .Values.env.bboxSizeTiles | quote }}
  MERGE_BATCH_SIZE: {{ .Values.env.mergeBatchSize | quote }}
  TASKS_BATCH_SIZE: {{ .Values.env.tasksBatchSize | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
{{- end }}
